# Generated by Django 5.2.13 on 2026-07-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_appsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=40)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('customer_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('ship_to_name', models.CharField(blank=True, default='', max_length=200)),
                ('ship_to_address', models.TextField(blank=True, default='')),
                ('challan_date', models.DateField()),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('place_of_supply', models.CharField(blank=True, default='TN (33)', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('terms', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-challan_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('sub_description', models.TextField(blank=True, default='')),
                ('hsn_sac', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.deliverychallan')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
