# Generated by Django 5.2.13 on 2026-07-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('receipt_to_name', models.CharField(max_length=200)),
                ('receipt_to_phone', models.CharField(blank=True, default='', max_length=40)),
                ('receipt_to_address', models.TextField(blank=True, default='')),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, default='Bank Transfer', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('terms', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('document_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('position', models.PositiveIntegerField(default=0)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expenses.paymentreceipt')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
