# Generated by Django 5.2.13 on 2026-07-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_paymentreceipt_paymentreceiptline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=40)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('customer_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('ship_to_name', models.CharField(blank=True, default='', max_length=200)),
                ('ship_to_address', models.TextField(blank=True, default='')),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('place_of_supply', models.CharField(blank=True, default='TN (33)', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('terms', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('sub_description', models.TextField(blank=True, default='')),
                ('hsn_sac', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('position', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.quote')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
