# Generated by Django 5.2.14 on 2026-07-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_billofsupply_taxinvoice_billofsupplyitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('hdfc', 'HDFC'), ('bob', 'Bank of Baroda')], db_index=True, max_length=10)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, default='')),
                ('ref_no', models.CharField(blank=True, default='', max_length=150)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('row_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bank statement entries',
                'ordering': ['-txn_date', '-id'],
            },
        ),
    ]
