# Generated by Django 5.2.14 on 2026-07-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_bankstatemententry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatemententry',
            name='balance_dc',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
