# Generated by Django 5.2.14 on 2026-07-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_bankstatemententry_balance_dc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatemententry',
            name='bank',
            field=models.CharField(choices=[('idfc', 'IDFC FIRST Bank'), ('bob', 'Bank of Baroda')], db_index=True, max_length=10),
        ),
    ]
