# Generated by Django 5.2.14 on 2026-08-03 07:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_rename_hdfc_to_idfc_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerPnl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('engg_count', models.PositiveIntegerField(default=1)),
                ('per_day_target', models.PositiveIntegerField(default=10)),
                ('per_call_rate', models.DecimalField(decimal_places=2, default=Decimal('350'), max_digits=10)),
                ('engg_salary', models.DecimalField(decimal_places=2, default=Decimal('25000'), max_digits=12)),
                ('total_working_days', models.PositiveIntegerField(default=30)),
                ('actual_working_days', models.PositiveIntegerField(default=25)),
                ('active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
