# Generated by Django 5.2.14 on 2026-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_engineerpnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='credit_payment_mode',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='debit_payment_mode',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentmodebalance',
            name='payment_mode',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
