# Generated by Django 5.2.14 on 2026-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_alter_expense_credit_payment_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleekBillInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=80, unique=True)),
                ('invoice_type', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('client_name', models.CharField(blank=True, default='', max_length=250)),
                ('client_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('client_phone', models.CharField(blank=True, default='', max_length=40)),
                ('client_email', models.CharField(blank=True, default='', max_length=150)),
                ('client_city', models.CharField(blank=True, default='', max_length=100)),
                ('client_state', models.CharField(blank=True, default='', max_length=100)),
                ('creator_name', models.CharField(blank=True, default='', max_length=150)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('dr_cr', models.CharField(blank=True, default='', max_length=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_mode', models.CharField(blank=True, default='', max_length=60)),
                ('payment_info', models.TextField(blank=True, default='')),
                ('financial_year', models.CharField(blank=True, default='', max_length=20)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sleek Bill invoices',
                'ordering': ['-issue_date', '-id'],
            },
        ),
    ]
