# Generated by Django 5.2.14 on 2026-08-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_sleekbillinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleekbillinvoice',
            name='pdf_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleekbillinvoice',
            name='pdf_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
